--- AUTO-GENERATED by tools/gen_roster.py - do not hand-edit.
--- Add or remove art in assets/ and re-run the script instead.

SMODS.Atlas {
    key = "aicandii",
    path = "aicandii.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "amalee",
    path = "amalee.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "aquwa",
    path = "aquwa.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "arar",
    path = "arar.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "arielle",
    path = "arielle.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "ariesakana",
    path = "ariesakana.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "augustanomoly",
    path = "augustanomoly.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "axialmatt",
    path = "axialmatt.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "baddaboom",
    path = "baddaboom.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "bao",
    path = "bao.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "bearthewitch",
    path = "bearthewitch.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "beepers",
    path = "beepers.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "beribug",
    path = "beribug.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "berrycrepe",
    path = "berrycrepe.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "birdyovo",
    path = "birdyovo.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "bluto",
    path = "bluto.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "bricky",
    path = "bricky.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "buffpup",
    path = "buffpup.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "camila",
    path = "camila.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "cerbervt",
    path = "cerbervt.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "chacha",
    path = "chacha.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "chibidoki",
    path = "chibidoki.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "clover",
    path = "clover.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "cottontail",
    path = "cottontail.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "crelly",
    path = "crelly.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "cweamcat",
    path = "cweamcat.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "cyyuvtuber",
    path = "cyyuvtuber.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "dejavudea",
    path = "dejavudea.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "demenishki",
    path = "demenishki.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "dooby",
    path = "dooby.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "el_xox",
    path = "el_xox.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "elorapard",
    path = "elorapard.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "fefe",
    path = "fefe.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "fraiki",
    path = "fraiki.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "fream",
    path = "fream.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "froggyloch",
    path = "froggyloch.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "fufu",
    path = "fufu.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "geega",
    path = "geega.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "giwi",
    path = "giwi.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "hannahhyrule",
    path = "hannahhyrule.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "harukakaribu",
    path = "harukakaribu.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "heavenlyfather",
    path = "heavenlyfather.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "henya",
    path = "henya.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "huntressspectre",
    path = "huntressspectre.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "ironmouse",
    path = "ironmouse.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "itsdeadlyboop",
    path = "itsdeadlyboop.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "jaws",
    path = "jaws.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "jaxvtuber",
    path = "jaxvtuber.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "jowol",
    path = "jowol.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "juniperactias",
    path = "juniperactias.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "kael",
    path = "kael.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "kairyucrocodile",
    path = "kairyucrocodile.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "kirana",
    path = "kirana.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "kiri",
    path = "kiri.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "kokonuts",
    path = "kokonuts.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "kourra",
    path = "kourra.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "kumi",
    path = "kumi.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "kyaree",
    path = "kyaree.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "laynalazar",
    path = "laynalazar.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "liffeh",
    path = "liffeh.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "limealicious",
    path = "limealicious.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "lucypyre",
    path = "lucypyre.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "maplechicken",
    path = "maplechicken.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "mariyume",
    path = "mariyume.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "maya",
    path = "maya.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "megalodon",
    path = "megalodon.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "meicha",
    path = "meicha.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "mellowmabel",
    path = "mellowmabel.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "michi",
    path = "michi.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "milky",
    path = "milky.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "mintfantome",
    path = "mintfantome.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "monikacinnyroll",
    path = "monikacinnyroll.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "moomerrily",
    path = "moomerrily.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "mooni",
    path = "mooni.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "motherv3",
    path = "motherv3.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "nagzz",
    path = "nagzz.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "nekrolina",
    path = "nekrolina.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "neuro",
    path = "neuro.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "nicoviras",
    path = "nicoviras.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "nihmune",
    path = "nihmune.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "nostro",
    path = "nostro.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "nyanners",
    path = "nyanners.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "onigiri",
    path = "onigiri.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "overezeggs",
    path = "overezeggs.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "pandabearlily",
    path = "pandabearlily.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "papamutt",
    path = "papamutt.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "pipi",
    path = "pipi.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "pomatomaster",
    path = "pomatomaster.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "pristinezero",
    path = "pristinezero.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "radiaactive",
    path = "radiaactive.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "radicalmari",
    path = "radicalmari.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "rainhoe",
    path = "rainhoe.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "rainyrentyn",
    path = "rainyrentyn.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "ray",
    path = "ray.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "rinpenrose",
    path = "rinpenrose.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "rosedoodle",
    path = "rosedoodle.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "rtgame",
    path = "rtgame.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "rynxryn",
    path = "rynxryn.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "saruei",
    path = "saruei.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "shenpai",
    path = "shenpai.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "shiabun",
    path = "shiabun.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "shoomimi",
    path = "shoomimi.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "shoto",
    path = "shoto.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "shylily",
    path = "shylily.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "sinder",
    path = "sinder.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "smugalana",
    path = "smugalana.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "snapscube",
    path = "snapscube.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "spite",
    path = "spite.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "spongeybuns",
    path = "spongeybuns.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "suto",
    path = "suto.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "vedal",
    path = "vedal.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "vexoria",
    path = "vexoria.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "vulpixie",
    path = "vulpixie.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "x3dustco",
    path = "x3dustco.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "yoclesh",
    path = "yoclesh.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "yokasiri",
    path = "yokasiri.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "yomiquinnely",
    path = "yomiquinnely.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "yuy_ix",
    path = "yuy_ix.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "yuzu",
    path = "yuzu.png",
    px = 71,
    py = 95,
}

SMODS.Atlas {
    key = "zentreya",
    path = "zentreya.png",
    px = 71,
    py = 95,
}
