--- AUTO-GENERATED by tools/gen_roster.py - do not hand-edit.
--- Add or remove art in assets/ and re-run the script instead.

--- Placeholder roster: every entry is a Common Joker with a stand-in
--- +Mult effect, so all art is loadable and testable in-game.
--- Jokers with real effects live in jokers/implemented.lua and are
--- deliberately absent from this list.

local ROSTER = {
    { key = "angelsteps", rarity = 1, cost = 4, mult = 4 },
    { key = "dokidomiki", rarity = 1, cost = 4, mult = 4 },
    { key = "dooby", rarity = 1, cost = 4, mult = 4 },
    { key = "elara", rarity = 1, cost = 4, mult = 4 },
    { key = "ellyvtuber", rarity = 1, cost = 4, mult = 4 },
    { key = "elorapard", rarity = 1, cost = 4, mult = 4 },
    { key = "fleshy", rarity = 1, cost = 4, mult = 4 },
    { key = "freyaamari", rarity = 1, cost = 4, mult = 4 },
    { key = "froot", rarity = 1, cost = 4, mult = 4 },
    { key = "giwi", rarity = 1, cost = 4, mult = 4 },
    { key = "glassesjournal", rarity = 1, cost = 4, mult = 4 },
    { key = "huntressspectre", rarity = 1, cost = 4, mult = 4 },
    { key = "juniperactias", rarity = 1, cost = 4, mult = 4 },
    { key = "kiri", rarity = 1, cost = 4, mult = 4 },
    { key = "lucypyre", rarity = 1, cost = 4, mult = 4 },
    { key = "mellowmabel", rarity = 1, cost = 4, mult = 4 },
    { key = "nekrolina", rarity = 1, cost = 4, mult = 4 },
    { key = "nicoviras", rarity = 1, cost = 4, mult = 4 },
    { key = "nyanners", rarity = 1, cost = 4, mult = 4 },
    { key = "obkatiekat", rarity = 1, cost = 4, mult = 4 },
    { key = "rainhoe", rarity = 1, cost = 4, mult = 4 },
    { key = "rainyrentyn", rarity = 1, cost = 4, mult = 4 },
    { key = "shaoanvt", rarity = 1, cost = 4, mult = 4 },
    { key = "smuggiess", rarity = 1, cost = 4, mult = 4 },
    { key = "snapscube", rarity = 1, cost = 4, mult = 4 },
    { key = "squchan", rarity = 1, cost = 4, mult = 4 },
    { key = "trickywi", rarity = 1, cost = 4, mult = 4 },
    { key = "uzuri", rarity = 1, cost = 4, mult = 4 },
    { key = "vantacrow_bringer", rarity = 1, cost = 4, mult = 4 },
    { key = "yoclesh", rarity = 1, cost = 4, mult = 4 },
}

for _, entry in ipairs(ROSTER) do
    SMODS.Joker {
        key = entry.key,
        atlas = entry.key,          -- one image, one atlas, single sprite
        pos = { x = 0, y = 0 },

        rarity = entry.rarity,
        cost = entry.cost,
        unlocked = true,
        discovered = true,
        blueprint_compat = true,
        eternal_compat = true,

        -- Placeholders are kept out of the shop and every booster pack until
        -- they have a real effect. SMODS.add_to_pool calls this, and
        -- get_current_pool gates the shop on it. They stay visible in the
        -- Collection. Move a joker to jokers/implemented.lua to let it spawn.
        in_pool = function(self, args) return false end,

        config = { extra = { mult = entry.mult } },

        loc_vars = function(self, info_queue, card)
            return { vars = { card.ability.extra.mult } }
        end,

        calculate = entry.calculate or function(self, card, context)
            if context.joker_main then
                return { mult = card.ability.extra.mult }
            end
        end,
    }
end
