--- AUTO-GENERATED by tools/gen_roster.py - do not hand-edit.
--- Add or remove art in assets/ and re-run the script instead.

--- Placeholder roster: every entry is a Common Joker with a stand-in
--- +Mult effect, so all art is loadable and testable in-game.
--- Jokers with real effects live in jokers/implemented.lua and are
--- deliberately absent from this list.

local ROSTER = {
    { key = "ariesakana", rarity = 1, cost = 4, mult = 4 },
    { key = "augustanomoly", rarity = 1, cost = 4, mult = 4 },
    { key = "buffpup", rarity = 1, cost = 4, mult = 4 },
    { key = "camila", rarity = 1, cost = 4, mult = 4 },
    { key = "cerbervt", rarity = 1, cost = 4, mult = 4 },
    { key = "chibidoki", rarity = 1, cost = 4, mult = 4 },
    { key = "clover", rarity = 1, cost = 4, mult = 4 },
    { key = "dooby", rarity = 1, cost = 4, mult = 4 },
    { key = "el_xox", rarity = 1, cost = 4, mult = 4 },
    { key = "elorapard", rarity = 1, cost = 4, mult = 4 },
    { key = "fefe", rarity = 1, cost = 4, mult = 4 },
    { key = "fream", rarity = 1, cost = 4, mult = 4 },
    { key = "fufu", rarity = 1, cost = 4, mult = 4 },
    { key = "geega", rarity = 1, cost = 4, mult = 4 },
    { key = "giwi", rarity = 1, cost = 4, mult = 4 },
    { key = "henya", rarity = 1, cost = 4, mult = 4 },
    { key = "huntressspectre", rarity = 1, cost = 4, mult = 4 },
    { key = "itsdeadlyboop", rarity = 1, cost = 4, mult = 4 },
    { key = "juniperactias", rarity = 1, cost = 4, mult = 4 },
    { key = "kael", rarity = 1, cost = 4, mult = 4 },
    { key = "kairyucrocodile", rarity = 1, cost = 4, mult = 4 },
    { key = "kirana", rarity = 1, cost = 4, mult = 4 },
    { key = "kiri", rarity = 1, cost = 4, mult = 4 },
    { key = "kourra", rarity = 1, cost = 4, mult = 4 },
    { key = "lucypyre", rarity = 1, cost = 4, mult = 4 },
    { key = "maplechicken", rarity = 1, cost = 4, mult = 4 },
    { key = "mariyume", rarity = 1, cost = 4, mult = 4 },
    { key = "mellowmabel", rarity = 1, cost = 4, mult = 4 },
    { key = "milky", rarity = 1, cost = 4, mult = 4 },
    { key = "monikacinnyroll", rarity = 1, cost = 4, mult = 4 },
    { key = "moomerrily", rarity = 1, cost = 4, mult = 4 },
    { key = "mooni", rarity = 1, cost = 4, mult = 4 },
    { key = "nagzz", rarity = 1, cost = 4, mult = 4 },
    { key = "nekrolina", rarity = 1, cost = 4, mult = 4 },
    { key = "nicoviras", rarity = 1, cost = 4, mult = 4 },
    { key = "nihmune", rarity = 1, cost = 4, mult = 4 },
    { key = "nostro", rarity = 1, cost = 4, mult = 4 },
    { key = "nyanners", rarity = 1, cost = 4, mult = 4 },
    { key = "pipi", rarity = 1, cost = 4, mult = 4 },
    { key = "pristinezero", rarity = 1, cost = 4, mult = 4 },
    { key = "radiaactive", rarity = 1, cost = 4, mult = 4 },
    { key = "radicalmari", rarity = 1, cost = 4, mult = 4 },
    { key = "rainhoe", rarity = 1, cost = 4, mult = 4 },
    { key = "rainyrentyn", rarity = 1, cost = 4, mult = 4 },
    { key = "ray", rarity = 1, cost = 4, mult = 4 },
    { key = "rinpenrose", rarity = 1, cost = 4, mult = 4 },
    { key = "rtgame", rarity = 1, cost = 4, mult = 4 },
    { key = "rynxryn", rarity = 1, cost = 4, mult = 4 },
    { key = "shenpai", rarity = 1, cost = 4, mult = 4 },
    { key = "shiabun", rarity = 1, cost = 4, mult = 4 },
    { key = "sinder", rarity = 1, cost = 4, mult = 4 },
    { key = "snapscube", rarity = 1, cost = 4, mult = 4 },
    { key = "spongeybuns", rarity = 1, cost = 4, mult = 4 },
    { key = "suto", rarity = 1, cost = 4, mult = 4 },
    { key = "vexoria", rarity = 1, cost = 4, mult = 4 },
    { key = "yoclesh", rarity = 1, cost = 4, mult = 4 },
    { key = "yokasiri", rarity = 1, cost = 4, mult = 4 },
}

for _, entry in ipairs(ROSTER) do
    SMODS.Joker {
        key = entry.key,
        atlas = entry.key,          -- one image, one atlas, single sprite
        pos = { x = 0, y = 0 },

        rarity = entry.rarity,
        cost = entry.cost,
        unlocked = true,
        discovered = true,
        blueprint_compat = true,
        eternal_compat = true,

        -- Placeholders are kept out of the shop and every booster pack until
        -- they have a real effect. SMODS.add_to_pool calls this, and
        -- get_current_pool gates the shop on it. They stay visible in the
        -- Collection. Move a joker to jokers/implemented.lua to let it spawn.
        in_pool = function(self, args) return false end,

        config = { extra = { mult = entry.mult } },

        loc_vars = function(self, info_queue, card)
            return { vars = { card.ability.extra.mult } }
        end,

        calculate = entry.calculate or function(self, card, context)
            if context.joker_main then
                return { mult = card.ability.extra.mult }
            end
        end,
    }
end
